# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Twirl"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

template: "simple"

logger: "console"

# template: "template_toolkit"
# engines:
#   template_toolkit:
#     start_tag: '[%'
#     end_tag:   '%]'

# Twitter API config
twitter_consumer_key: "3rTaVDBhnRWT4hiesGEeYGEBP"
twitter_consumer_secret: "mAADsf30S1pVe1YhwfAIQDMjJkg237cl9JMEh3LLY69fbWAPn3"
twitter_access_token: "20342122-rYKugIVLH6wBhWaRqLz3vrYPdZCvkpjjvPXaEHoXa"
twitter_access_token_secret: "gDKBPcUjh033iXzJCuysZw1wfzdIcTbSGHVqXTvCD1qaU"

# Redis client config
redis_server: "barreleye.redistogo.com:11162"
redis_password: "c551885f0afec1a9bbed62b12136b2d1"
